import type { PricingType } from '@aitoolhunt/shared';

export const seedCategories = [
  { name: 'AI Writing', slug: 'ai-writing', description: 'AI-powered writing assistants, content generators, and copywriting tools', iconName: 'pen-tool' },
  { name: 'AI Image', slug: 'ai-image', description: 'AI image generators, editors, and enhancement tools', iconName: 'image' },
  { name: 'AI Video', slug: 'ai-video', description: 'AI video creation, editing, and generation tools', iconName: 'video' },
  { name: 'AI Coding', slug: 'ai-coding', description: 'AI coding assistants, code generators, and developer tools', iconName: 'code' },
  { name: 'AI Productivity', slug: 'ai-productivity', description: 'AI tools for productivity, automation, and workflow optimization', iconName: 'zap' },
  { name: 'AI Marketing', slug: 'ai-marketing', description: 'AI marketing tools for SEO, social media, and campaigns', iconName: 'megaphone' },
  { name: 'AI Voice', slug: 'ai-voice', description: 'AI voice generation, text-to-speech, and audio tools', iconName: 'mic' },
  { name: 'AI Research', slug: 'ai-research', description: 'AI research assistants, data analysis, and knowledge tools', iconName: 'search' },
  { name: 'AI Design', slug: 'ai-design', description: 'AI design tools for UI/UX, graphics, and creative work', iconName: 'palette' },
  { name: 'AI Chatbot', slug: 'ai-chatbot', description: 'AI chatbots, conversational AI, and customer service tools', iconName: 'message-circle' },
];

interface SeedTool {
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  categorySlug: string;
  websiteUrl: string;
  pricingType: PricingType;
  features: string[];
  useCases: string[];
  isFeatured: boolean;
  tags: string[];
}

export const seedTools: SeedTool[] = [
  // AI Writing
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    description: 'ChatGPT is an AI language model by OpenAI that can generate human-like text, answer questions, write code, and assist with a wide variety of tasks. It supports multiple languages and can be customized for specific use cases.',
    shortDescription: 'AI conversational assistant by OpenAI for writing, coding, and problem-solving',
    categorySlug: 'ai-writing',
    websiteUrl: 'https://chat.openai.com',
    pricingType: 'freemium',
    features: ['Text generation', 'Code writing', 'Language translation', 'Content summarization', 'Creative writing', 'Data analysis'],
    useCases: ['Content creation', 'Customer support', 'Education', 'Research assistance'],
    isFeatured: true,
    tags: ['chatbot', 'writing', 'coding', 'openai'],
  },
  {
    name: 'Jasper',
    slug: 'jasper',
    description: 'Jasper is an AI content creation platform designed for marketing teams. It helps create blog posts, social media content, emails, and ad copy with brand voice consistency.',
    shortDescription: 'AI content creation platform for marketing teams',
    categorySlug: 'ai-writing',
    websiteUrl: 'https://www.jasper.ai',
    pricingType: 'paid',
    features: ['Brand voice', 'Template library', 'SEO optimization', 'Team collaboration', 'Content repurposing'],
    useCases: ['Blog writing', 'Ad copy', 'Email marketing', 'Social media'],
    isFeatured: true,
    tags: ['marketing', 'content', 'copywriting'],
  },
  {
    name: 'Copy.ai',
    slug: 'copy-ai',
    description: 'Copy.ai is an AI-powered copywriting tool that helps marketers and businesses create high-converting marketing copy, blog content, and social media posts.',
    shortDescription: 'AI copywriting tool for marketing and sales content',
    categorySlug: 'ai-writing',
    websiteUrl: 'https://www.copy.ai',
    pricingType: 'freemium',
    features: ['Sales copy', 'Blog content', 'Social media posts', 'Email templates', 'Workflow automation'],
    useCases: ['Sales emails', 'Product descriptions', 'Blog posts', 'Ad copy'],
    isFeatured: false,
    tags: ['copywriting', 'marketing', 'sales'],
  },
  {
    name: 'Grammarly',
    slug: 'grammarly',
    description: 'Grammarly is an AI-powered writing assistant that checks grammar, spelling, punctuation, and style. It offers tone detection and clarity improvements for professional communication.',
    shortDescription: 'AI writing assistant for grammar, clarity, and tone',
    categorySlug: 'ai-writing',
    websiteUrl: 'https://www.grammarly.com',
    pricingType: 'freemium',
    features: ['Grammar check', 'Tone detection', 'Plagiarism checker', 'Style suggestions', 'Browser extension'],
    useCases: ['Email writing', 'Academic writing', 'Professional communication', 'Content editing'],
    isFeatured: true,
    tags: ['grammar', 'writing', 'editing', 'proofreading'],
  },
  {
    name: 'Writesonic',
    slug: 'writesonic',
    description: 'Writesonic is an AI writing tool that generates SEO-optimized content including articles, blog posts, landing pages, and product descriptions.',
    shortDescription: 'AI writing tool for SEO-optimized content generation',
    categorySlug: 'ai-writing',
    websiteUrl: 'https://writesonic.com',
    pricingType: 'freemium',
    features: ['Article writer', 'SEO optimization', 'Landing page copy', 'Paraphrasing', 'AI art generation'],
    useCases: ['Blog posts', 'Landing pages', 'Product descriptions', 'SEO content'],
    isFeatured: false,
    tags: ['seo', 'content', 'writing'],
  },
  // AI Image
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'Midjourney is an AI image generation tool that creates stunning artwork from text descriptions. Known for its artistic quality and creative output.',
    shortDescription: 'AI art generator creating stunning images from text prompts',
    categorySlug: 'ai-image',
    websiteUrl: 'https://www.midjourney.com',
    pricingType: 'paid',
    features: ['Text-to-image', 'Style customization', 'Upscaling', 'Variation generation', 'Pan and zoom'],
    useCases: ['Digital art', 'Concept design', 'Marketing visuals', 'Book covers'],
    isFeatured: true,
    tags: ['art', 'image-generation', 'creative'],
  },
  {
    name: 'DALL-E 3',
    slug: 'dall-e-3',
    description: 'DALL-E 3 by OpenAI generates highly detailed and accurate images from text descriptions. Integrated with ChatGPT for conversational image creation.',
    shortDescription: 'OpenAI image generator with high accuracy and detail',
    categorySlug: 'ai-image',
    websiteUrl: 'https://openai.com/dall-e-3',
    pricingType: 'paid',
    features: ['Text-to-image', 'ChatGPT integration', 'High resolution', 'Style control', 'Inpainting'],
    useCases: ['Marketing materials', 'Social media graphics', 'Product mockups', 'Illustrations'],
    isFeatured: true,
    tags: ['image-generation', 'openai', 'creative'],
  },
  {
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    description: 'Stable Diffusion is an open-source AI image generation model that can be run locally or through various cloud services. Highly customizable with community models.',
    shortDescription: 'Open-source AI image generation model with community support',
    categorySlug: 'ai-image',
    websiteUrl: 'https://stability.ai',
    pricingType: 'free',
    features: ['Open source', 'Local deployment', 'Custom models', 'ControlNet', 'Inpainting'],
    useCases: ['Art creation', 'Game assets', 'Product photography', 'Animation'],
    isFeatured: false,
    tags: ['open-source', 'image-generation', 'self-hosted'],
  },
  {
    name: 'Remove.bg',
    slug: 'remove-bg',
    description: 'Remove.bg uses AI to automatically remove backgrounds from images in seconds. Supports bulk processing and integrations with design tools.',
    shortDescription: 'AI-powered automatic background removal from images',
    categorySlug: 'ai-image',
    websiteUrl: 'https://www.remove.bg',
    pricingType: 'freemium',
    features: ['Background removal', 'Bulk processing', 'API access', 'HD quality', 'Plugin integrations'],
    useCases: ['E-commerce photos', 'Profile pictures', 'Marketing materials', 'Design work'],
    isFeatured: false,
    tags: ['background-removal', 'photo-editing', 'e-commerce'],
  },
  {
    name: 'Canva AI',
    slug: 'canva-ai',
    description: 'Canva AI integrates artificial intelligence into the popular design platform, offering Magic Write, text-to-image generation, and AI-powered design suggestions.',
    shortDescription: 'AI-powered design platform for creating visual content',
    categorySlug: 'ai-image',
    websiteUrl: 'https://www.canva.com',
    pricingType: 'freemium',
    features: ['Magic Write', 'Text-to-image', 'Background remover', 'Magic Eraser', 'Design templates'],
    useCases: ['Social media graphics', 'Presentations', 'Marketing materials', 'Brand design'],
    isFeatured: false,
    tags: ['design', 'templates', 'social-media'],
  },
  // AI Video
  {
    name: 'Runway',
    slug: 'runway',
    description: 'Runway is an AI-powered creative suite for video editing and generation. Features include text-to-video, video-to-video transformation, and advanced editing tools.',
    shortDescription: 'AI creative suite for video generation and editing',
    categorySlug: 'ai-video',
    websiteUrl: 'https://runwayml.com',
    pricingType: 'freemium',
    features: ['Text-to-video', 'Video editing', 'Green screen', 'Motion tracking', 'Style transfer'],
    useCases: ['Film production', 'Social media content', 'Music videos', 'Advertising'],
    isFeatured: true,
    tags: ['video-generation', 'editing', 'creative'],
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    description: 'Synthesia creates AI-generated videos with digital avatars that speak in multiple languages. Used for training videos, marketing content, and corporate communications.',
    shortDescription: 'AI video platform with digital avatars for professional content',
    categorySlug: 'ai-video',
    websiteUrl: 'https://www.synthesia.io',
    pricingType: 'paid',
    features: ['AI avatars', 'Multi-language', 'Custom avatars', 'Screen recording', 'Templates'],
    useCases: ['Training videos', 'Marketing', 'Corporate comms', 'Product demos'],
    isFeatured: false,
    tags: ['avatars', 'training', 'enterprise'],
  },
  {
    name: 'HeyGen',
    slug: 'heygen',
    description: 'HeyGen is an AI video generator that creates professional spokesperson videos. It features talking avatars, voice cloning, and multilingual video production.',
    shortDescription: 'AI video generator with talking avatars and voice cloning',
    categorySlug: 'ai-video',
    websiteUrl: 'https://www.heygen.com',
    pricingType: 'freemium',
    features: ['Talking avatars', 'Voice cloning', 'Video translation', 'Custom templates', 'API access'],
    useCases: ['Sales videos', 'Social media', 'E-learning', 'Customer support'],
    isFeatured: false,
    tags: ['avatars', 'voice-cloning', 'marketing'],
  },
  {
    name: 'Luma AI',
    slug: 'luma-ai',
    description: 'Luma AI specializes in 3D capture and video generation. It can create photorealistic 3D models from videos and generate AI-powered visual content.',
    shortDescription: 'AI platform for 3D capture and photorealistic video generation',
    categorySlug: 'ai-video',
    websiteUrl: 'https://lumalabs.ai',
    pricingType: 'freemium',
    features: ['3D capture', 'NeRF technology', 'Video generation', 'API access', 'iOS app'],
    useCases: ['3D modeling', 'Product visualization', 'Real estate', 'Gaming'],
    isFeatured: false,
    tags: ['3d', 'video-generation', 'photogrammetry'],
  },
  // AI Coding
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'GitHub Copilot is an AI pair programmer that helps developers write code faster. It provides real-time code suggestions, generates functions, and understands context across files.',
    shortDescription: 'AI pair programmer for real-time code suggestions and generation',
    categorySlug: 'ai-coding',
    websiteUrl: 'https://github.com/features/copilot',
    pricingType: 'paid',
    features: ['Code completion', 'Multi-language support', 'IDE integration', 'Chat interface', 'Code explanation'],
    useCases: ['Software development', 'Code review', 'Learning to code', 'Rapid prototyping'],
    isFeatured: true,
    tags: ['coding', 'github', 'ide', 'pair-programming'],
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    description: 'Cursor is an AI-powered code editor built on VS Code. It features intelligent code generation, editing, and debugging with deep codebase understanding.',
    shortDescription: 'AI-first code editor with intelligent code generation',
    categorySlug: 'ai-coding',
    websiteUrl: 'https://cursor.sh',
    pricingType: 'freemium',
    features: ['AI code generation', 'Codebase understanding', 'Multi-file editing', 'Chat interface', 'VS Code compatible'],
    useCases: ['Full-stack development', 'Code refactoring', 'Bug fixing', 'Learning'],
    isFeatured: true,
    tags: ['code-editor', 'ai-coding', 'ide'],
  },
  {
    name: 'Claude Code',
    slug: 'claude-code',
    description: 'Claude Code by Anthropic is an AI coding assistant that operates directly in the terminal. It can understand entire codebases, make multi-file changes, and execute commands.',
    shortDescription: 'Terminal-based AI coding agent by Anthropic',
    categorySlug: 'ai-coding',
    websiteUrl: 'https://docs.anthropic.com/en/docs/claude-code',
    pricingType: 'paid',
    features: ['Terminal-native', 'Codebase understanding', 'Multi-file editing', 'Command execution', 'Git integration'],
    useCases: ['Software development', 'Code refactoring', 'Bug fixing', 'Project scaffolding'],
    isFeatured: true,
    tags: ['terminal', 'anthropic', 'agent', 'coding'],
  },
  {
    name: 'Replit AI',
    slug: 'replit-ai',
    description: 'Replit AI integrates artificial intelligence into the Replit online IDE, providing code generation, debugging assistance, and an AI agent that can build entire applications.',
    shortDescription: 'AI-powered online IDE for building and deploying applications',
    categorySlug: 'ai-coding',
    websiteUrl: 'https://replit.com',
    pricingType: 'freemium',
    features: ['Online IDE', 'AI code generation', 'Instant deployment', 'Collaboration', 'Database integration'],
    useCases: ['Web development', 'Prototyping', 'Learning', 'Hackathons'],
    isFeatured: false,
    tags: ['ide', 'cloud', 'deployment'],
  },
  {
    name: 'Tabnine',
    slug: 'tabnine',
    description: 'Tabnine is an AI code completion tool that runs locally for privacy. It supports all major programming languages and integrates with popular IDEs.',
    shortDescription: 'Privacy-focused AI code completion running locally',
    categorySlug: 'ai-coding',
    websiteUrl: 'https://www.tabnine.com',
    pricingType: 'freemium',
    features: ['Local processing', 'Multi-language', 'IDE plugins', 'Team learning', 'Privacy-focused'],
    useCases: ['Enterprise development', 'Secure coding', 'Code completion', 'Team productivity'],
    isFeatured: false,
    tags: ['code-completion', 'privacy', 'enterprise'],
  },
  // AI Productivity
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'Notion AI enhances the Notion workspace with AI-powered features including writing assistance, summarization, action item extraction, and database automation.',
    shortDescription: 'AI-enhanced workspace for notes, docs, and project management',
    categorySlug: 'ai-productivity',
    websiteUrl: 'https://www.notion.so/product/ai',
    pricingType: 'freemium',
    features: ['Writing assistance', 'Summarization', 'Action items', 'Translation', 'Database fills'],
    useCases: ['Project management', 'Documentation', 'Meeting notes', 'Knowledge base'],
    isFeatured: true,
    tags: ['workspace', 'notes', 'project-management'],
  },
  {
    name: 'Otter.ai',
    slug: 'otter-ai',
    description: 'Otter.ai is an AI meeting assistant that provides real-time transcription, meeting summaries, and automated action items from conversations.',
    shortDescription: 'AI meeting assistant for transcription and note-taking',
    categorySlug: 'ai-productivity',
    websiteUrl: 'https://otter.ai',
    pricingType: 'freemium',
    features: ['Real-time transcription', 'Meeting summaries', 'Action items', 'Speaker identification', 'Zoom integration'],
    useCases: ['Meeting notes', 'Interviews', 'Lectures', 'Team collaboration'],
    isFeatured: false,
    tags: ['transcription', 'meetings', 'notes'],
  },
  {
    name: 'Zapier AI',
    slug: 'zapier-ai',
    description: 'Zapier AI enables workflow automation powered by artificial intelligence. Create automated workflows between thousands of apps using natural language instructions.',
    shortDescription: 'AI-powered workflow automation connecting thousands of apps',
    categorySlug: 'ai-productivity',
    websiteUrl: 'https://zapier.com',
    pricingType: 'freemium',
    features: ['Workflow automation', 'AI actions', 'App integrations', 'Natural language setup', 'Conditional logic'],
    useCases: ['Business automation', 'Data sync', 'Lead management', 'Content publishing'],
    isFeatured: false,
    tags: ['automation', 'workflow', 'integration'],
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description: 'Perplexity AI is an AI-powered search engine that provides detailed answers with cited sources. It combines web search with AI to deliver accurate, up-to-date information.',
    shortDescription: 'AI search engine providing cited answers from the web',
    categorySlug: 'ai-productivity',
    websiteUrl: 'https://www.perplexity.ai',
    pricingType: 'freemium',
    features: ['AI search', 'Source citations', 'Follow-up questions', 'Collections', 'API access'],
    useCases: ['Research', 'Fact-checking', 'Learning', 'Content research'],
    isFeatured: true,
    tags: ['search', 'research', 'citations'],
  },
  {
    name: 'Reclaim AI',
    slug: 'reclaim-ai',
    description: 'Reclaim AI is a smart calendar assistant that automatically schedules tasks, habits, and meetings. It optimizes your schedule for productivity.',
    shortDescription: 'AI calendar assistant for automatic schedule optimization',
    categorySlug: 'ai-productivity',
    websiteUrl: 'https://reclaim.ai',
    pricingType: 'freemium',
    features: ['Smart scheduling', 'Task automation', 'Habit tracking', 'Meeting optimization', 'Google Calendar sync'],
    useCases: ['Time management', 'Team scheduling', 'Work-life balance', 'Productivity'],
    isFeatured: false,
    tags: ['calendar', 'scheduling', 'time-management'],
  },
  // AI Marketing
  {
    name: 'Surfer SEO',
    slug: 'surfer-seo',
    description: 'Surfer SEO is an AI-powered SEO tool that analyzes search results and provides content optimization recommendations to improve rankings.',
    shortDescription: 'AI SEO tool for content optimization and ranking improvement',
    categorySlug: 'ai-marketing',
    websiteUrl: 'https://surferseo.com',
    pricingType: 'paid',
    features: ['Content editor', 'SERP analysis', 'Keyword research', 'Content audit', 'AI writer'],
    useCases: ['SEO optimization', 'Content writing', 'Competitor analysis', 'Keyword strategy'],
    isFeatured: true,
    tags: ['seo', 'content', 'optimization'],
  },
  {
    name: 'Semrush',
    slug: 'semrush',
    description: 'Semrush is an all-in-one digital marketing suite with AI features for SEO, content marketing, competitor research, and advertising campaign management.',
    shortDescription: 'All-in-one AI marketing suite for SEO and digital marketing',
    categorySlug: 'ai-marketing',
    websiteUrl: 'https://www.semrush.com',
    pricingType: 'paid',
    features: ['Keyword research', 'Site audit', 'Position tracking', 'Content marketing', 'Competitor analysis'],
    useCases: ['SEO strategy', 'PPC campaigns', 'Content planning', 'Market research'],
    isFeatured: false,
    tags: ['seo', 'marketing', 'analytics'],
  },
  {
    name: 'Buffer AI',
    slug: 'buffer-ai',
    description: 'Buffer AI enhances social media management with AI-generated post suggestions, optimal posting times, and content repurposing across platforms.',
    shortDescription: 'AI social media management with smart scheduling',
    categorySlug: 'ai-marketing',
    websiteUrl: 'https://buffer.com',
    pricingType: 'freemium',
    features: ['AI post creation', 'Multi-platform', 'Analytics', 'Scheduling', 'Content calendar'],
    useCases: ['Social media management', 'Content scheduling', 'Brand building', 'Engagement'],
    isFeatured: false,
    tags: ['social-media', 'scheduling', 'content'],
  },
  {
    name: 'AdCreative.ai',
    slug: 'adcreative-ai',
    description: 'AdCreative.ai uses AI to generate high-converting ad creatives for social media, display, and search campaigns. It analyzes performance data to improve results.',
    shortDescription: 'AI ad creative generator for high-converting campaigns',
    categorySlug: 'ai-marketing',
    websiteUrl: 'https://www.adcreative.ai',
    pricingType: 'paid',
    features: ['Ad generation', 'Performance scoring', 'Brand kit', 'A/B testing', 'Multi-platform'],
    useCases: ['Social media ads', 'Display advertising', 'E-commerce', 'Performance marketing'],
    isFeatured: false,
    tags: ['advertising', 'creative', 'performance'],
  },
  // AI Voice
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'ElevenLabs offers AI voice synthesis with natural-sounding text-to-speech, voice cloning, and multilingual support. Used for content creation and accessibility.',
    shortDescription: 'AI voice synthesis with natural text-to-speech and voice cloning',
    categorySlug: 'ai-voice',
    websiteUrl: 'https://elevenlabs.io',
    pricingType: 'freemium',
    features: ['Text-to-speech', 'Voice cloning', 'Multi-language', 'API access', 'Voice library'],
    useCases: ['Podcasts', 'Audiobooks', 'Video narration', 'Accessibility'],
    isFeatured: true,
    tags: ['tts', 'voice-cloning', 'audio'],
  },
  {
    name: 'Murf AI',
    slug: 'murf-ai',
    description: 'Murf AI is a text-to-speech platform with studio-quality AI voices. It offers voice-over generation for videos, presentations, and e-learning content.',
    shortDescription: 'Studio-quality AI voice-over generator for professional content',
    categorySlug: 'ai-voice',
    websiteUrl: 'https://murf.ai',
    pricingType: 'freemium',
    features: ['AI voices', 'Voice customization', 'Video sync', 'Multi-language', 'Team workspace'],
    useCases: ['E-learning', 'Marketing videos', 'Presentations', 'IVR systems'],
    isFeatured: false,
    tags: ['voice-over', 'tts', 'professional'],
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'Descript is an AI-powered audio and video editor that lets you edit media by editing text. Features include transcription, screen recording, and AI voice generation.',
    shortDescription: 'AI audio/video editor with text-based editing',
    categorySlug: 'ai-voice',
    websiteUrl: 'https://www.descript.com',
    pricingType: 'freemium',
    features: ['Text-based editing', 'Transcription', 'Screen recording', 'AI voice', 'Filler word removal'],
    useCases: ['Podcast editing', 'Video production', 'Transcription', 'Social media clips'],
    isFeatured: false,
    tags: ['editing', 'podcast', 'transcription'],
  },
  // AI Research
  {
    name: 'Consensus',
    slug: 'consensus',
    description: 'Consensus is an AI search engine for scientific research. It uses language models to analyze and summarize findings from peer-reviewed papers.',
    shortDescription: 'AI search engine for scientific research and academic papers',
    categorySlug: 'ai-research',
    websiteUrl: 'https://consensus.app',
    pricingType: 'freemium',
    features: ['Paper search', 'AI summaries', 'Consensus meter', 'Study snapshots', 'Citation export'],
    useCases: ['Academic research', 'Literature review', 'Evidence-based decisions', 'Fact-checking'],
    isFeatured: false,
    tags: ['research', 'academic', 'papers'],
  },
  {
    name: 'Elicit',
    slug: 'elicit',
    description: 'Elicit is an AI research assistant that helps find, summarize, and extract data from research papers. It automates systematic literature reviews.',
    shortDescription: 'AI research assistant for finding and analyzing academic papers',
    categorySlug: 'ai-research',
    websiteUrl: 'https://elicit.com',
    pricingType: 'freemium',
    features: ['Paper discovery', 'Data extraction', 'Summarization', 'Systematic reviews', 'Custom columns'],
    useCases: ['Literature reviews', 'Research synthesis', 'Grant writing', 'Thesis research'],
    isFeatured: false,
    tags: ['research', 'papers', 'literature-review'],
  },
  {
    name: 'Semantic Scholar',
    slug: 'semantic-scholar',
    description: 'Semantic Scholar by AI2 is a free AI-powered research tool that helps find relevant scientific literature. It provides AI-generated summaries and citation analysis.',
    shortDescription: 'Free AI-powered academic search engine by AI2',
    categorySlug: 'ai-research',
    websiteUrl: 'https://www.semanticscholar.org',
    pricingType: 'free',
    features: ['Paper search', 'Citation graphs', 'AI summaries', 'Author profiles', 'API access'],
    useCases: ['Academic research', 'Citation analysis', 'Research trends', 'Paper discovery'],
    isFeatured: false,
    tags: ['academic', 'citations', 'free'],
  },
  {
    name: 'Scite',
    slug: 'scite',
    description: 'Scite uses AI to help researchers understand how research papers cite each other, distinguishing between supporting, contradicting, and mentioning citations.',
    shortDescription: 'AI tool for understanding research citation context',
    categorySlug: 'ai-research',
    websiteUrl: 'https://scite.ai',
    pricingType: 'paid',
    features: ['Smart citations', 'Citation context', 'Reference checks', 'Custom dashboards', 'Browser extension'],
    useCases: ['Research validation', 'Literature review', 'Academic writing', 'Peer review'],
    isFeatured: false,
    tags: ['citations', 'validation', 'academic'],
  },
  // AI Design
  {
    name: 'Figma AI',
    slug: 'figma-ai',
    description: 'Figma AI brings artificial intelligence into the popular design tool, offering features like AI-generated designs, auto layout suggestions, and smart component creation.',
    shortDescription: 'AI-powered features within the Figma design platform',
    categorySlug: 'ai-design',
    websiteUrl: 'https://www.figma.com',
    pricingType: 'freemium',
    features: ['AI design generation', 'Auto layout', 'Smart components', 'Content generation', 'Prototyping'],
    useCases: ['UI design', 'Prototyping', 'Design systems', 'Collaboration'],
    isFeatured: true,
    tags: ['design', 'ui', 'prototyping'],
  },
  {
    name: 'Framer AI',
    slug: 'framer-ai',
    description: 'Framer AI enables users to generate complete websites from text descriptions. It creates responsive, animated designs that can be published directly.',
    shortDescription: 'AI website builder that generates sites from text descriptions',
    categorySlug: 'ai-design',
    websiteUrl: 'https://www.framer.com',
    pricingType: 'freemium',
    features: ['AI site generation', 'Responsive design', 'Animations', 'CMS', 'Custom domains'],
    useCases: ['Landing pages', 'Portfolio sites', 'Marketing sites', 'Prototyping'],
    isFeatured: false,
    tags: ['website-builder', 'no-code', 'design'],
  },
  {
    name: 'Looka',
    slug: 'looka',
    description: 'Looka uses AI to generate professional logos and brand identity assets. Users provide preferences and receive customized logo designs.',
    shortDescription: 'AI logo and brand identity generator',
    categorySlug: 'ai-design',
    websiteUrl: 'https://looka.com',
    pricingType: 'freemium',
    features: ['Logo generation', 'Brand kit', 'Business cards', 'Social media kit', 'Color palettes'],
    useCases: ['Logo design', 'Brand identity', 'Startup branding', 'Rebranding'],
    isFeatured: false,
    tags: ['logo', 'branding', 'identity'],
  },
  // AI Chatbot
  {
    name: 'Claude',
    slug: 'claude',
    description: 'Claude by Anthropic is an AI assistant focused on being helpful, harmless, and honest. It excels at long-form content, analysis, coding, and nuanced conversations.',
    shortDescription: 'Anthropic AI assistant for analysis, writing, and coding',
    categorySlug: 'ai-chatbot',
    websiteUrl: 'https://claude.ai',
    pricingType: 'freemium',
    features: ['Long context', 'Code analysis', 'Document processing', 'Vision capabilities', 'Artifacts'],
    useCases: ['Research', 'Writing', 'Coding', 'Analysis', 'Education'],
    isFeatured: true,
    tags: ['chatbot', 'anthropic', 'analysis'],
  },
  {
    name: 'Google Gemini',
    slug: 'google-gemini',
    description: 'Google Gemini is a multimodal AI model that can understand and generate text, images, audio, and code. It is integrated into Google products and services.',
    shortDescription: 'Google multimodal AI for text, images, and code',
    categorySlug: 'ai-chatbot',
    websiteUrl: 'https://gemini.google.com',
    pricingType: 'freemium',
    features: ['Multimodal', 'Google integration', 'Code generation', 'Image understanding', 'Real-time info'],
    useCases: ['Search assistance', 'Coding', 'Content creation', 'Research'],
    isFeatured: true,
    tags: ['chatbot', 'google', 'multimodal'],
  },
  {
    name: 'Poe',
    slug: 'poe',
    description: 'Poe by Quora provides access to multiple AI chatbots including ChatGPT, Claude, Gemini, and community-created bots in one platform.',
    shortDescription: 'Multi-model AI chatbot platform by Quora',
    categorySlug: 'ai-chatbot',
    websiteUrl: 'https://poe.com',
    pricingType: 'freemium',
    features: ['Multiple models', 'Custom bots', 'Bot creation', 'Knowledge bases', 'API access'],
    useCases: ['AI comparison', 'Custom assistants', 'Research', 'Education'],
    isFeatured: false,
    tags: ['multi-model', 'chatbot', 'platform'],
  },
  {
    name: 'Character.AI',
    slug: 'character-ai',
    description: 'Character.AI lets users create and interact with AI characters. It powers personalized conversations with fictional and historical characters.',
    shortDescription: 'AI platform for creating and chatting with AI characters',
    categorySlug: 'ai-chatbot',
    websiteUrl: 'https://character.ai',
    pricingType: 'freemium',
    features: ['Character creation', 'Roleplay', 'Voice chat', 'Group chats', 'Character rooms'],
    useCases: ['Entertainment', 'Education', 'Creative writing', 'Language practice'],
    isFeatured: false,
    tags: ['characters', 'roleplay', 'entertainment'],
  },
  // More tools for volume
  {
    name: 'Suno',
    slug: 'suno',
    description: 'Suno is an AI music generation platform that creates songs with vocals, instruments, and lyrics from text descriptions. Users can specify genre and mood.',
    shortDescription: 'AI music generator creating songs from text descriptions',
    categorySlug: 'ai-voice',
    websiteUrl: 'https://suno.com',
    pricingType: 'freemium',
    features: ['Song generation', 'Custom lyrics', 'Genre selection', 'Voice styles', 'Remix'],
    useCases: ['Music creation', 'Content background music', 'Jingles', 'Creative projects'],
    isFeatured: false,
    tags: ['music', 'audio', 'creative'],
  },
  {
    name: 'Tome',
    slug: 'tome',
    description: 'Tome is an AI presentation tool that generates complete slide decks from text prompts. It creates visually compelling narratives for business and creative use.',
    shortDescription: 'AI presentation generator creating visual narratives',
    categorySlug: 'ai-productivity',
    websiteUrl: 'https://tome.app',
    pricingType: 'freemium',
    features: ['AI presentations', 'Template library', 'Embedding support', 'Analytics', 'Collaboration'],
    useCases: ['Business presentations', 'Pitch decks', 'Project proposals', 'Education'],
    isFeatured: false,
    tags: ['presentations', 'slides', 'business'],
  },
  {
    name: 'Gamma',
    slug: 'gamma',
    description: 'Gamma is an AI-powered tool for creating presentations, documents, and webpages. It generates polished content from simple prompts.',
    shortDescription: 'AI tool for creating presentations, docs, and webpages',
    categorySlug: 'ai-productivity',
    websiteUrl: 'https://gamma.app',
    pricingType: 'freemium',
    features: ['AI generation', 'Templates', 'Analytics', 'Custom branding', 'Export options'],
    useCases: ['Presentations', 'Reports', 'Landing pages', 'Proposals'],
    isFeatured: false,
    tags: ['presentations', 'documents', 'no-code'],
  },
  {
    name: 'v0 by Vercel',
    slug: 'v0-vercel',
    description: 'v0 by Vercel is an AI-powered UI generation tool that creates React components from text and image descriptions. It produces production-ready code using shadcn/ui.',
    shortDescription: 'AI UI generator creating React components from descriptions',
    categorySlug: 'ai-coding',
    websiteUrl: 'https://v0.dev',
    pricingType: 'freemium',
    features: ['UI generation', 'React components', 'shadcn/ui', 'Image-to-code', 'Iterative refinement'],
    useCases: ['Frontend development', 'Prototyping', 'UI design', 'Component creation'],
    isFeatured: false,
    tags: ['ui', 'react', 'frontend', 'vercel'],
  },
  {
    name: 'Photoroom',
    slug: 'photoroom',
    description: 'Photoroom is an AI photo editing app that removes backgrounds, creates product photos, and generates marketing images for e-commerce.',
    shortDescription: 'AI photo editor for product photography and e-commerce',
    categorySlug: 'ai-image',
    websiteUrl: 'https://www.photoroom.com',
    pricingType: 'freemium',
    features: ['Background removal', 'Product photos', 'AI scenes', 'Batch editing', 'API'],
    useCases: ['E-commerce', 'Social media', 'Marketing', 'Product catalogs'],
    isFeatured: false,
    tags: ['e-commerce', 'photo-editing', 'product'],
  },
];
